const data=window.portfolio;const sections=['projects','expertise','experience','contact'];let lang='fr',category=0,query='',active='projects';const state={open:new Set()};try{lang=localStorage.getItem('ao-lang')==='en'?'en':'fr';document.body.classList.toggle('light',localStorage.getItem('ao-theme')==='light')}catch{}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const index=()=>lang==='fr'?0:1;const fold=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function documentLinks(documents=[]){
  const t=data[lang],i=index();
  const available=documents.filter(d=>d.href&&t.documentLabels[d.kind]);
  if(!available.length)return '';
  return `<div class="document-links" role="group" aria-label="${escapeHTML(t.documents)}">${available.map(d=>`<div class="document-item"><a class="document-link" href="${escapeHTML(d.href)}" target="_blank" rel="noopener"><span>${escapeHTML(d.label?d.label[i]:t.documentLabels[d.kind])}</span>${d.format?`<span class="document-format">${escapeHTML(d.format)}</span>`:''}</a>${d.caption?`<p class="document-caption">${escapeHTML(d.caption[i])}</p>`:''}</div>`).join('')}</div>`;
}
function experienceDetails(items,open){
  const t=data[lang],i=index();
  if(!items.length)return '';
  return `<details class="experience-details" ${open?'open':''}><summary>${escapeHTML(t.experienceDetails)}</summary><div class="experience-work">${items.map(p=>`<section class="experience-achievement" id="work-${p.id}"><h4>${escapeHTML(p.title[i])}</h4><p>${escapeHTML(p.contribution[i])}</p><p>${escapeHTML(p.detail[i])}</p><div class="tags">${p.stack.map(s=>`<span>${escapeHTML(s)}</span>`).join('')}</div>${p.repo?`<a class="repo-link" href="${escapeHTML(p.repo)}" target="_blank" rel="noopener">${escapeHTML(p.repoType==='report'?t.report:t.repo)}</a>`:''}</section>`).join('')}</div></details>`;
}
function renderExperience(){
  const t=data[lang];
  const opened=new Set([...document.querySelectorAll('.experience-details[open]')].map(d=>d.closest('.timeline-item').id));
  document.getElementById('timeline').innerHTML=t.experience.map(x=>{
    const work=data.experienceWork[x[5]];
    return `<article id="experience-${x[5]}" class="timeline-item"><span class="timeline-year">${escapeHTML(x[0])}</span><h3>${escapeHTML(x[1])}</h3><p class="timeline-role">${escapeHTML(x[2])}</p><span class="timeline-location">${escapeHTML(x[3])}</span><p class="experience-summary">${escapeHTML(x[4])}</p>${documentLinks(work.documents)}${experienceDetails(work.items,opened.has('experience-'+x[5]))}${window.caseStudies.preview(x[5],lang)}</article>`;
  }).join('');
}
function updateNav(){document.querySelectorAll('[data-section]').forEach(a=>{const current=a.dataset.section===active;a.classList.toggle('active',current);if(current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}
function updateTheme(){const light=document.body.classList.contains('light');document.getElementById('theme').setAttribute('aria-pressed',String(light));document.getElementById('theme').setAttribute('aria-label',data[lang].switchTheme);document.querySelector('meta[name="theme-color"]').content=light?'#f6f8fd':'#0b1220'}
function projectHighlights(p,i){
  return p.highlights?.length ? '<ul class="project-highlights">'+p.highlights.map(x=>'<li>'+escapeHTML(x[i])+'</li>').join('')+'</ul>' : '';
}
function projectSections(p,i){
  if(!p.sections?.length)return '';
  const sections=p.sections.map((section,n)=>'<details class="project-section" '+(n===0?'open':'')+'><summary><span>'+escapeHTML(section.title[i])+'</span><span class="project-status">'+escapeHTML(section.status[i])+'</span></summary><ul>'+section.items.map(item=>'<li>'+escapeHTML(item[i])+'</li>').join('')+'</ul></details>').join('');
  const links=(p.links||[]).map(link=>'<a href="'+escapeHTML(link.href)+'" target="_blank" rel="noopener">'+escapeHTML(link.label[i])+' ↗</a>').join('');
  return '<div class="project-sections">'+sections+'</div><div class="project-source-links">'+links+'</div>';
}
function renderProjects(){const t=data[lang],i=index();state.open=new Set([...document.querySelectorAll('.project-card > details[open]')].map(x=>x.closest('.project-card').dataset.id));document.getElementById('project-grid').innerHTML=data.projects.map(p=>`<article id="project-${p.id}" class="project-card ${p.id==='flow'?'featured':''}" data-id="${p.id}" data-cats="${p.cats.join(',')}"><div class="project-meta"><span>${escapeHTML(p.context[i])}</span><span>${escapeHTML(p.year==='Master'&&lang==='en'?'MSc':p.year)}</span></div><p class="project-kind">${escapeHTML(t.filters[p.cats[0]])}</p><h3>${escapeHTML(p.title[i])}</h3><p class="project-summary">${escapeHTML(p.summary[i])}</p>${projectHighlights(p,i)}${p.vision?`<p class="project-vision">${escapeHTML(p.vision[i])}</p>`:''}${window.caseStudies.preview(p.id,lang)}<div class="tags">${p.stack.map(s=>`<span>${escapeHTML(s)}</span>`).join('')}</div><details ${state.open.has(p.id)?'open':''}><summary>${escapeHTML(p.sections?.length?(i===0?'Fonctionnalités, architecture & feuille de route':'Features, architecture & roadmap'):t.details)}</summary><h4>${t.contribution}</h4><p>${escapeHTML(p.contribution[i])}</p><p>${escapeHTML(p.detail[i])}</p>${projectSections(p,i)}</details>${p.repo?`<a class="repo-link" href="${escapeHTML(p.repo)}" target="_blank" rel="noopener">${p.repoType==='report'?t.report:t.repo}</a>`:''}${documentLinks(p.documents)}</article>`).join('');applyFilters()}
function applyFilters(){const t=data[lang];let count=0;const term=fold(query.trim());data.projects.forEach(p=>{const text=fold([...p.title,...p.summary,...p.contribution,...p.detail,...p.stack,...p.context,...(p.vision||[]),...(p.highlights||[]).flat(),...(p.sections||[]).flatMap(s=>[...s.title,...s.status,...s.items.flat()])].join(' '));const show=(!category||p.cats.includes(category))&&(!term||text.includes(term));document.getElementById('project-'+p.id).hidden=!show;if(show)count++});document.getElementById('result-count').textContent=`${count} / ${data.projects.length} ${t.count}`;document.getElementById('empty').hidden=count>0;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.filter)===category)))}
function render(){const t=data[lang],i=index();document.documentElement.lang=lang;document.title='Amine Oubaidi — '+(lang==='fr'?'Ingénieur IA & Data Scientist':'AI Engineer & Data Scientist');document.querySelector('meta[name="description"]').content=lang==='fr'?'Portfolio d’Amine Oubaidi : Deep Learning, vision, multimodal, MLOps, recherche et ingénierie des données.':'Amine Oubaidi’s portfolio: Deep Learning, vision, multimodal learning, MLOps, research and data engineering.';document.querySelectorAll('[data-t]').forEach(x=>x.textContent=t[x.dataset.t]);document.querySelectorAll('[data-html]').forEach(x=>x.innerHTML=t[x.dataset.html]);['fr','en'].forEach(l=>document.getElementById(l).setAttribute('aria-pressed',String(l===lang)));const nav=sections.map((s,n)=>`<a href="#${s}" data-section="${s}">${t.nav[n]}</a>`).join('');document.querySelector('.nav').innerHTML=nav;document.getElementById('mobile-nav').innerHTML=nav;document.getElementById('menu').setAttribute('aria-label',t.menu);document.getElementById('search').placeholder=t.searchPlaceholder;document.getElementById('filters').setAttribute('aria-label',lang==='fr'?'Filtrer les projets':'Filter projects');document.getElementById('filters').innerHTML=t.filters.map((x,n)=>`<button data-filter="${n}" aria-pressed="${category===n}">${x}</button>`).join('');document.getElementById('ribbon').innerHTML=t.ribbon.map(x=>`<span>${x}</span>`).join('');document.getElementById('skills').innerHTML=data.skills.map((g,n)=>`<article class="skill-card"><div class="skill-heading"><span class="skill-index">${String(n+1).padStart(2,'0')}</span><div><h3>${g.title[i]}</h3><p>${g.note[i]}</p></div></div><div class="skill-pills">${g.items.map(x=>`<span>${escapeHTML(x)}</span>`).join('')}</div></article>`).join('');document.getElementById('practice').innerHTML=t.practice.map(x=>`<span>${x}</span>`).join('');renderExperience();document.getElementById('education').innerHTML=t.education.map(x=>`<article class="education-item"><span class="education-year">${x[0]}</span><h4>${x[1]}</h4><p>${x[2]}</p><p>${x[3]}</p></article>`).join('');document.getElementById('certifications').innerHTML=data.certs.map(x=>`<li>${x}</li>`).join('');renderProjects();updateTheme();updateNav();window.caseStudies.refresh()}
render();['fr','en'].forEach(l=>document.getElementById(l).addEventListener('click',()=>{lang=l;try{localStorage.setItem('ao-lang',lang)}catch{}render()}));document.getElementById('theme').addEventListener('click',()=>{document.body.classList.toggle('light');try{localStorage.setItem('ao-theme',document.body.classList.contains('light')?'light':'dark')}catch{}updateTheme()});document.getElementById('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;category=Number(b.dataset.filter);applyFilters()});document.getElementById('search').addEventListener('input',e=>{query=e.target.value;applyFilters()});function resetFilters(){category=0;query='';document.getElementById('search').value='';applyFilters()}document.getElementById('reset').addEventListener('click',resetFilters);document.getElementById('menu').addEventListener('click',()=>{const nav=document.getElementById('mobile-nav');nav.hidden=!nav.hidden;const button=document.getElementById('menu');button.setAttribute('aria-expanded',String(!nav.hidden));button.setAttribute('aria-label',nav.hidden?data[lang].menu:data[lang].closeMenu)});function closeMenu(){document.getElementById('mobile-nav').hidden=true;document.getElementById('menu').setAttribute('aria-expanded','false');document.getElementById('menu').setAttribute('aria-label',data[lang].menu)}document.getElementById('mobile-nav').addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});let scheduled=false;window.addEventListener('scroll',()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{let current=sections[0];for(const id of sections)if(document.getElementById(id).getBoundingClientRect().top<200)current=id;active=current;updateNav();scheduled=false})},{passive:true});
